--CREATE SEQUENCE ID_INC INCREMENT BY 1 START WITH 1;


CREATE TABLE ROLES
(
  ROLE_ID INT NOT NULL
, ROLE_NAME VARCHAR2(50) NOT NULL
, CONSTRAINT ROLES_PK PRIMARY KEY
  (
    ROLE_ID
  )
  ENABLE
);

insert into roles values(1, 'GUEST');
insert into roles values(2, 'USER');
insert into roles values(3, 'ADMINISTRATOR');
commit;

CREATE TABLE USERS
(
  EMAIL VARCHAR2(120) NOT NULL
, FIRST_NAME VARCHAR2(45) NOT NULL
, LAST_NAME VARCHAR2(45) NOT NULL
, ROLE INT NOT NULL
, PASSWORD VARCHAR2(25) NOT NULL
, CONSTRAINT USERS_PK PRIMARY KEY
  (
    EMAIL
  )
  ENABLE
);
ALTER TABLE USERS
ADD CONSTRAINT USERS_FK FOREIGN KEY
(
  ROLE
)
REFERENCES ROLES
(
  ROLE_ID
)
ENABLE;

-- ########################### STATUSES ###########################
CREATE TABLE STATUSES
(
  STATUS_ID INT NOT NULL
, STATUS_NAME VARCHAR2(30) NOT NULL
, CONSTRAINT STATUSES_PK PRIMARY KEY
  (
    STATUS_ID
  )
  ENABLE
);

insert into statuses values(1, 'New');
insert into statuses values(2, 'Assigned');
insert into statuses values(3, 'In Progress');
insert into statuses values(4, 'Resolved');
insert into statuses values(5, 'Closed');
insert into statuses values(6, 'Reopened');
commit;
-- #################################################################


CREATE TABLE RESOLUTIONS
(
  RESOLUTION_ID INT NOT NULL
, RESOLUTION_NAME VARCHAR2(30) NOT NULL
, CONSTRAINT RESOLUTIONS_PK PRIMARY KEY
  (
    RESOLUTION_ID
  )
  ENABLE
);

insert into resolutions values(1, 'Fixed');
insert into resolutions values(2, 'Invalid');
insert into resolutions values(3, 'Wontfix');
insert into resolutions values(4, 'Worksforme');
commit;

CREATE TABLE PRIORITIES
(
  PRIORITY_ID INT NOT NULL
, PRIORITY_NAME VARCHAR2(30) NOT NULL
, CONSTRAINT PRIORITIES_PK PRIMARY KEY
  (
    PRIORITY_ID
  )
  ENABLE
);

insert into priorities values(1, 'Critical');
insert into priorities values(2, 'Major');
insert into priorities values(3, 'Important');
insert into priorities values(4, 'Minor');
commit;

CREATE TABLE TYPES
(
  TYPE_ID INT NOT NULL
, TYPE_NAME VARCHAR2(30) NOT NULL
, CONSTRAINT TYPES_PK PRIMARY KEY
  (
    TYPE_ID
  )
  ENABLE
);

insert into types values(1, 'Cosmetic');
insert into types values(2, 'Bug');
insert into types values(3, 'Feature');
insert into types values(4, 'Performance');
commit;

CREATE TABLE MANAGERS
(
  MANAGER_ID INT NOT NULL
, MANAGER_NAME VARCHAR2(60) NOT NULL
, CONSTRAINT MANAGERS_PK PRIMARY KEY
  (
    MANAGER_ID
  )
  ENABLE
);

CREATE TABLE PROJECTS
(
  PROJECT_ID INT NOT NULL
, PROJECT_NAME VARCHAR2(50) NOT NULL
, DESCRIPTION VARCHAR2(100) NOT NULL
, BUILD VARCHAR2(20) NOT NULL
, MANAGER INT NOT NULL
, CONSTRAINT PROJECTS_PK PRIMARY KEY
  (
    PROJECT_ID
  )
  ENABLE
);

ALTER TABLE PROJECTS
ADD CONSTRAINT PROJECTS_FK FOREIGN KEY
(
  PROJECT_ID
)
REFERENCES MANAGERS
(
  MANAGER_ID
)
ON DELETE CASCADE ENABLE;




CREATE TABLE ISSUES
(
  ISSUE_ID INT NOT NULL
, CREATE_DATE DATE NOT NULL
, CREATED_BY VARCHAR2(120) NOT NULL
, MODIFY_DATE DATE NOT NULL
, MODIFYED_BY VARCHAR2(20) NOT NULL
, SUMMARY VARCHAR2(30) NOT NULL
, DESCRIPTION VARCHAR2(255) NOT NULL
, STATUS INT NOT NULL
, RESOLUTION INT
, TYPE INT NOT NULL
, PRIORITY INT NOT NULL
, PROJECT INT NOT NULL
, BUILD_FOUND VARCHAR2(20) NOT NULL
, ASSIGNEE VARCHAR2(20)
, CONSTRAINT ISSUES_PK PRIMARY KEY
  (
    ISSUE_ID
  )
  ENABLE
);

ALTER TABLE ISSUES
ADD CONSTRAINT ISSUES_CREATED_BY_FK FOREIGN KEY
(
  CREATED_BY
)
REFERENCES USERS
(
  EMAIL
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ISSUES
ADD CONSTRAINT ISSUES_MODIFYED_BY_FK FOREIGN KEY
(
  MODIFYED_BY
)
REFERENCES USERS
(
  EMAIL
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ISSUES
ADD CONSTRAINT ISSUES_PRIORITY_FK FOREIGN KEY
(
  PRIORITY
)
REFERENCES PRIORITIES
(
  PRIORITY_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ISSUES
ADD CONSTRAINT ISSUES_PROJECT_FK FOREIGN KEY
(
  PROJECT
)
REFERENCES PROJECTS
(
  PROJECT_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ISSUES
ADD CONSTRAINT ISSUES_RESOLUTION_FK FOREIGN KEY
(
  RESOLUTION
)
REFERENCES RESOLUTIONS
(
  RESOLUTION_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ISSUES
ADD CONSTRAINT ISSUES_STATUS_FK FOREIGN KEY
(
  STATUS
)
REFERENCES STATUSES
(
  STATUS_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ISSUES
ADD CONSTRAINT ISSUES_TYPE_FK FOREIGN KEY
(
  TYPE
)
REFERENCES TYPES
(
  TYPE_ID
)
ON DELETE CASCADE ENABLE;